# Generated by Django 2.2.10 on 2021-09-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210908_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
