# Generated by Django 2.2.10 on 2021-09-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_answerer_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'ответ', 'verbose_name_plural': 'ответы'},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'user_id')},
        ),
    ]
