# Generated by Django 2.2.10 on 2021-09-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210909_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answerer_count',
            new_name='answered_count',
        ),
    ]
