# Generated by Django 2.2.10 on 2021-09-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210909_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='числовой ID'),
        ),
    ]
